title: All things "P"
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
All things "P"

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
